//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shops
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class product
    {
        public int id { get; set; }
        public string manufacturer { get; set; }
        public string colour { get; set; }
        public string model { get; set; }
        public Nullable<int> capacity { get; set; }
        public Nullable<int> mileage { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> shop_id { get; set; }
    
        public virtual shop shop { get; set; }
    }
}
